### ISSUE TITLE
Sass error - import/*

### ISSUE THREAD

**Issue by Ezra-Siton-UIX** [Gottwik/enduro_mirror#9] opened 2017-11-08 04:36 UTC
**System**: `Windows` | **version**: `enduro 1.4.41`
First on windows now the instalation works fine https://github.com/Gottwik/Enduro/issues/128 (I close this topic).

`@import '/variables/*';`
Throw this error:
![image](https://user-images.githubusercontent.com/16711871/32531666-dd7be0a2-c44d-11e7-8fbd-e4a233219126.png)

I don't think the (asterisk ) `/*;` is part of the core  **sccs** without extention like this one:
- https://www.npmjs.com/package/gulp-sass-glob
- https://stackoverflow.com/questions/4778627/is-it-possible-to-import-a-whole-directory-in-sass-using-import

**Comment by jj-owens** [comment] 2017-11-08 12:13
Please see https://github.com/Gottwik/Enduro/issues/153

**Comment by Ezra-Siton-UIX** [comment] 2017-11-12 00:57
Thanks. OK. But I think the theme should work fine without any extras/Changes. 

In uikit instead of /* they made file call "__import" with the full list of files
https://github.com/uikit/uikit/blob/develop/src/scss/theme/_import.scss

Than in the "parent" you only need to call to this file:
https://github.com/uikit/uikit/blob/develop/src/scss/uikit.scss

**Comment by Gottwik** [comment] 2017-11-15 09:33
@Ezra-Siton-UIX  I fixed this. It was caused by bootstrap version mixup

enduro uses https://github.com/mathisonian/gulp-sass-bulk-import to handle those `*` imports. It's nice because you can just add sass files and don't have to include them each time.

I'll close this, feel free to reopen or create new ticket if this is not fixed

**Closed by Gottwik** 2017-11-15 09:33 UTC

**Comment by Ezra-Siton-UIX** [comment] 2017-11-16 00:15
Thanks. Great!
